# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8b63283b1e0b7d64b7f90b2c3c324028"
name = "products-vectro"
handle = "products-vectro"
application_url = "https://handmade-trivia-ontario-ciao.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-d0bd7a75.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_product_listings,read_products"

[auth]
redirect_urls = [
  "https://handmade-trivia-ontario-ciao.trycloudflare.com/auth/callback",
  "https://handmade-trivia-ontario-ciao.trycloudflare.com/auth/shopify/callback",
  "https://handmade-trivia-ontario-ciao.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
